[package]
name = "substrate_ibc_client"
version = "0.1.0"
authors = ["Chorus One"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sc-consensus-babe = "0.8.0-alpha.5"
sc-finality-grandpa = "0.8.0-alpha.5"
sp-finality-grandpa = "2.0.0-alpha.5"
sp-runtime = "2.0.0-alpha.5"